y = 10+3j
x = {"ball", 12, 14,}
z = ["fruit", "food"]
q = "michael"
list = ['bsbi', 5757, 3.14, 'mike', 90.57]
tinylist = [987, 'ayo_ola']
for i in range(5, 10):
    print(i)
3 * 7
15 ** 79
101 + 40000
200 / 700
5600 // 2
900 % 87
1000 - 1
70 != 32
90 == 19
10 > 20
40 < 00
number = 10 

if number > 0:
    print(f"{number} is positive")
print("hello")
number = 0

if number < 0:
    print(f"number {number} is positive")
    
elif number == 0:
    print(f"{number} is zero")
    
else:
    print(f"{number} is negative")
number = 15

if number > 0:
    print(f"number {number} is positive")

elif number == 0:
    print(f"{number} is zero")
    
else:
    print(f"{number} is negative")
number = 50
number = number - 10    
number = 20
number %=9
brand = "new_apple"
brand = "zara"
print((10 > 5)
     and 1 < 3
     and "A" == "A")